### ISSUE TITLE
Can't compile on Ubuntu

### ISSUE THREAD

**Issue by luisvalenzuelar** [RoSh-23/Index-Creator#1]
Hi there, compilation ends in error:

```
collect2: error: ld returned 1 exit status
```

Full output [here](https://paste.ubuntu.com/p/2xcqVh3SnJ/).

**Comment by RoSh-23** [comment]
Hi,
- The program has been written in C++. 
- Therefore it can be compiled successfully only using GCC compiler for C++ which is g++.
- GCC is a compiler toolkit for various programming language.
- Thanks for raising this point.
- I will clear any ambiguity in the README section.

**Comment by RoSh-23** [comment]
Hi,
After your issue, I found out more errors and have made certain other changes in almost all files. If you want to run this, please ensure that you use the latest version of the code and files.

**Comment by luisvalenzuelar** [comment]
Thanks! Can compile now.
